"""empty message

Revision ID: 19bf3e1db56c
Revises: f8505f3d8e72
Create Date: 2026-10-10 01:20:32.553807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bf3e1db56c'
down_revision: Union[str, Sequence[str], None] = 'f8505f3d8e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('behaivor_evalhist_child_id_fkey'), 'behavior_evalhist', type_='foreignkey')
    op.create_foreign_key(None, 'behavior_evalhist', 'child', ['child_id'], ['child_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('child_data_child_id_fkey'), 'child_data', type_='foreignkey')
    op.create_foreign_key(None, 'child_data', 'child', ['child_id'], ['child_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('child_distance_child_id_1_fkey'), 'child_distance', type_='foreignkey')
    op.drop_constraint(op.f('child_distance_child_id_2_fkey'), 'child_distance', type_='foreignkey')
    op.create_foreign_key(None, 'child_distance', 'child', ['child_id_2'], ['child_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'child_distance', 'child', ['child_id_1'], ['child_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('child_distance_evalhist_child_id_1_fkey'), 'child_distance_evalhist', type_='foreignkey')
    op.drop_constraint(op.f('child_distance_evalhist_child_id_2_fkey'), 'child_distance_evalhist', type_='foreignkey')
    op.create_foreign_key(None, 'child_distance_evalhist', 'child', ['child_id_2'], ['child_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'child_distance_evalhist', 'child', ['child_id_1'], ['child_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'child_distance_evalhist', type_='foreignkey')
    op.drop_constraint(None, 'child_distance_evalhist', type_='foreignkey')
    op.create_foreign_key(op.f('child_distance_evalhist_child_id_2_fkey'), 'child_distance_evalhist', 'child', ['child_id_2'], ['child_id'])
    op.create_foreign_key(op.f('child_distance_evalhist_child_id_1_fkey'), 'child_distance_evalhist', 'child', ['child_id_1'], ['child_id'])
    op.drop_constraint(None, 'child_distance', type_='foreignkey')
    op.drop_constraint(None, 'child_distance', type_='foreignkey')
    op.create_foreign_key(op.f('child_distance_child_id_2_fkey'), 'child_distance', 'child', ['child_id_2'], ['child_id'])
    op.create_foreign_key(op.f('child_distance_child_id_1_fkey'), 'child_distance', 'child', ['child_id_1'], ['child_id'])
    op.drop_constraint(None, 'child_data', type_='foreignkey')
    op.create_foreign_key(op.f('child_data_child_id_fkey'), 'child_data', 'child', ['child_id'], ['child_id'])
    op.drop_constraint(None, 'behavior_evalhist', type_='foreignkey')
    op.create_foreign_key(op.f('behaivor_evalhist_child_id_fkey'), 'behavior_evalhist', 'child', ['child_id'], ['child_id'])
    # ### end Alembic commands ###
