"""empty message

Revision ID: 30c3a72997ef
Revises: bcefe69bcf3b
Create Date: 2026-10-04 02:34:01.376899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c3a72997ef'
down_revision: Union[str, Sequence[str], None] = 'bcefe69bcf3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('_', sa.Boolean(), nullable=False),
    sa.Column('activity_max_data_minutes', sa.Integer(), nullable=False),
    sa.Column('anomaly_threshold_ratio', sa.Float(), nullable=False),
    sa.Column('baseline_min_data_minutes', sa.Integer(), nullable=False),
    sa.Column('baseline_max_days', sa.Integer(), nullable=False),
    sa.Column('relatedness_max_history', sa.Integer(), nullable=False),
    sa.Column('relatedness_max_steps_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint('CAST(_ AS INTEGER) = 1', name='no_multiple_config'),
    sa.PrimaryKeyConstraint('_')
    )
    op.rename_table("behaivor_evalhist", "behavior_evalhist")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.rename_table("behavior_evalhist", "behaivor_evalhist")
    # ### end Alembic commands ###
