"""empty message

Revision ID: 45233a8ab06e
Revises: a910696b81ad
Create Date: 2026-09-24 02:26:44.792460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45233a8ab06e'
down_revision: Union[str, Sequence[str], None] = 'a910696b81ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_distance_evalhist',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('evaluated', sa.Enum('NA', 'ALONE', 'SAME_BEHAVIOR', 'SAME_ROOM', name='childdistanceevaluationenum'), nullable=False),
    sa.Column('child_id_1', sa.Integer(), nullable=False),
    sa.Column('child_id_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id_1'], ['child.child_id'], ),
    sa.ForeignKeyConstraint(['child_id_2'], ['child.child_id'], ),
    sa.PrimaryKeyConstraint('date', 'child_id_1', 'child_id_2')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child_distance_evalhist')
    # ### end Alembic commands ###
