"""empty message

Revision ID: 53f7585f66fd
Revises: 
Create Date: 2026-09-01 16:59:50.233678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f7585f66fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('child_id')
    )
    op.create_table('teacher',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('pw_hash', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('child_data',
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.child_id'], ),
    sa.PrimaryKeyConstraint('child_id', 'date', 'steps')
    )
    op.create_table('child_distance',
    sa.Column('child_id_1', sa.String(), nullable=False),
    sa.Column('child_id_2', sa.String(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.CheckConstraint('child_id_1 < child_id_2', name='child_id_order'),
    sa.ForeignKeyConstraint(['child_id_1'], ['child.child_id'], ),
    sa.ForeignKeyConstraint(['child_id_2'], ['child.child_id'], ),
    sa.PrimaryKeyConstraint('child_id_1', 'child_id_2', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child_distance')
    op.drop_table('child_data')
    op.drop_table('teacher')
    op.drop_table('child')
    # ### end Alembic commands ###
