"""empty message

Revision ID: 59a7d533810e
Revises: 45233a8ab06e
Create Date: 2026-09-25 15:26:04.085931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a7d533810e'
down_revision: Union[str, Sequence[str], None] = '45233a8ab06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behaivor_evalhist',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('behavior_acce', sa.Enum('SITTING', 'STANDING', name='childbehavioracceenum'), nullable=False),
    sa.Column('behavior_acce_confidence', sa.Float(), nullable=False),
    sa.Column('behavior_pedo', sa.Enum('SLOW', 'NORMAL', 'STOP', name='childbehaviorpedoenum'), nullable=False),
    sa.Column('behavior_pedo_confidence', sa.Float(), nullable=False),
    sa.Column('activity', sa.Integer(), nullable=False),
    sa.Column('activity_confidence', sa.Float(), nullable=False),
    sa.Column('baseline_steps_10min_median', sa.Float(), nullable=True),
    sa.Column('baseline_steps_10min_mad_scale', sa.Float(), nullable=True),
    sa.Column('baseline_activity_mean_proxy_median', sa.Float(), nullable=True),
    sa.Column('baseline_activity_mean_proxy_mad_scale', sa.Float(), nullable=True),
    sa.Column('baseline_acc_std_median', sa.Float(), nullable=True),
    sa.Column('baseline_acc_std_mad_scale', sa.Float(), nullable=True),
    sa.Column('baseline_gyro_mean_median', sa.Float(), nullable=True),
    sa.Column('baseline_gyro_mean_mad_scale', sa.Float(), nullable=True),
    sa.Column('baseline_mag_mean_median', sa.Float(), nullable=True),
    sa.Column('baseline_mag_mean_mad_scale', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.child_id'], ),
    sa.PrimaryKeyConstraint('child_id', 'date')
    )
    op.add_column('child_distance_evalhist', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('child_distance_evalhist', sa.Column('score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_distance_evalhist', 'score')
    op.drop_column('child_distance_evalhist', 'confidence')
    op.drop_table('behaivor_evalhist')
    # ### end Alembic commands ###
