"""empty message

Revision ID: a910696b81ad
Revises: 9b2c4d6e7f80
Create Date: 2026-09-18 19:18:33.184104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a910696b81ad'
down_revision: Union[str, Sequence[str], None] = '9b2c4d6e7f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_data', sa.Column('ax', sa.Float(), nullable=False))
    op.add_column('child_data', sa.Column('ay', sa.Float(), nullable=False))
    op.add_column('child_data', sa.Column('az', sa.Float(), nullable=False))
    op.add_column('child_data', sa.Column('gx', sa.Float(), nullable=False))
    op.add_column('child_data', sa.Column('gy', sa.Float(), nullable=False))
    op.add_column('child_data', sa.Column('gz', sa.Float(), nullable=False))
    op.add_column('child_data', sa.Column('mx', sa.Float(), nullable=False))
    op.add_column('child_data', sa.Column('my', sa.Float(), nullable=False))
    op.add_column('child_data', sa.Column('mz', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_data', 'mz')
    op.drop_column('child_data', 'my')
    op.drop_column('child_data', 'mx')
    op.drop_column('child_data', 'gz')
    op.drop_column('child_data', 'gy')
    op.drop_column('child_data', 'gx')
    op.drop_column('child_data', 'az')
    op.drop_column('child_data', 'ay')
    op.drop_column('child_data', 'ax')
    # ### end Alembic commands ###
