"""empty message

Revision ID: bcefe69bcf3b
Revises: 
Create Date: 2026-09-30 17:23:53.539808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcefe69bcf3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_class',
    sa.Column('class_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('class_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teacher',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('pw_hash', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('child',
    sa.Column('child_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_class.class_id'], ),
    sa.PrimaryKeyConstraint('child_id')
    )
    op.create_table('behaivor_evalhist',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('behavior_acce', sa.Enum('SITTING', 'STANDING', name='childbehavioracceenum'), nullable=False),
    sa.Column('behavior_acce_confidence', sa.Float(), nullable=False),
    sa.Column('behavior_pedo', sa.Enum('SLOW', 'NORMAL', 'STOP', name='childbehaviorpedoenum'), nullable=False),
    sa.Column('behavior_pedo_confidence', sa.Float(), nullable=False),
    sa.Column('activity', sa.Integer(), nullable=False),
    sa.Column('activity_confidence', sa.Float(), nullable=False),
    sa.Column('baseline_steps_10min_median', sa.Float(), nullable=True),
    sa.Column('baseline_steps_10min_mad_scale', sa.Float(), nullable=True),
    sa.Column('baseline_activity_mean_proxy_median', sa.Float(), nullable=True),
    sa.Column('baseline_activity_mean_proxy_mad_scale', sa.Float(), nullable=True),
    sa.Column('baseline_acc_std_median', sa.Float(), nullable=True),
    sa.Column('baseline_acc_std_mad_scale', sa.Float(), nullable=True),
    sa.Column('baseline_gyro_mean_median', sa.Float(), nullable=True),
    sa.Column('baseline_gyro_mean_mad_scale', sa.Float(), nullable=True),
    sa.Column('baseline_mag_mean_median', sa.Float(), nullable=True),
    sa.Column('baseline_mag_mean_mad_scale', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.child_id'], ),
    sa.PrimaryKeyConstraint('child_id', 'date')
    )
    op.create_table('child_data',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('ax', sa.Float(), nullable=False),
    sa.Column('ay', sa.Float(), nullable=False),
    sa.Column('az', sa.Float(), nullable=False),
    sa.Column('gx', sa.Float(), nullable=False),
    sa.Column('gy', sa.Float(), nullable=False),
    sa.Column('gz', sa.Float(), nullable=False),
    sa.Column('mx', sa.Float(), nullable=False),
    sa.Column('my', sa.Float(), nullable=False),
    sa.Column('mz', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.child_id'], ),
    sa.PrimaryKeyConstraint('child_id', 'date', 'steps')
    )
    op.create_table('child_distance',
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('child_id_1', sa.Integer(), nullable=False),
    sa.Column('child_id_2', sa.Integer(), nullable=False),
    sa.CheckConstraint('child_id_1 < child_id_2', name='child_id_order'),
    sa.ForeignKeyConstraint(['child_id_1'], ['child.child_id'], ),
    sa.ForeignKeyConstraint(['child_id_2'], ['child.child_id'], ),
    sa.PrimaryKeyConstraint('date', 'child_id_1', 'child_id_2')
    )
    op.create_table('child_distance_evalhist',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('evaluated', sa.Enum('NA', 'ALONE', 'SAME_BEHAVIOR', 'SAME_ROOM', name='childdistanceevaluationenum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('child_id_1', sa.Integer(), nullable=False),
    sa.Column('child_id_2', sa.Integer(), nullable=False),
    sa.CheckConstraint('child_id_1 < child_id_2', name='child_id_order'),
    sa.ForeignKeyConstraint(['child_id_1'], ['child.child_id'], ),
    sa.ForeignKeyConstraint(['child_id_2'], ['child.child_id'], ),
    sa.PrimaryKeyConstraint('date', 'child_id_1', 'child_id_2')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child_distance_evalhist')
    op.drop_table('child_distance')
    op.drop_table('child_data')
    op.drop_table('behaivor_evalhist')
    op.drop_table('child')
    op.drop_table('teacher')
    op.drop_table('school_class')
    # ### end Alembic commands ###
