"""empty message

Revision ID: c9fe9fde9f53
Revises: 30c3a72997ef
Create Date: 2026-10-06 01:28:05.102081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9fe9fde9f53'
down_revision: Union[str, Sequence[str], None] = '30c3a72997ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vapid_key',
    sa.Column('_', sa.Boolean(), nullable=False),
    sa.Column('key_der', sa.LargeBinary(), nullable=False),
    sa.CheckConstraint('CAST(_ AS INTEGER) = 1', name='no_multiple_keys'),
    sa.PrimaryKeyConstraint('_')
    )
    op.create_table('webpush_subinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webpush_subinfo')
    op.drop_table('vapid_key')
    # ### end Alembic commands ###
